Repository aio-libs/frozenlist, pull requests merged in 2023-12, with the labels that each got.

#560 📦 Move packaging to PEP 517 in-tree backend
  .github/workflows/ci-cd.yml
  .github/workflows/reusable-build-wheel.yml
  .pre-commit-config.yaml
  CHANGES/560.contrib.rst
  CHANGES/560.packaging.rst
  MANIFEST.in
  Makefile
  README.rst
  packaging/README.md
  packaging/pep517_backend/__init__.py
  packaging/pep517_backend/__main__.py
  packaging/pep517_backend/_backend.py
  packaging/pep517_backend/_compat.py
  packaging/pep517_backend/_cython_configuration.py
  packaging/pep517_backend/_transformers.py
  packaging/pep517_backend/cli.py
  packaging/pep517_backend/hooks.py
  pyproject.toml
  requirements/dev.txt
  setup.cfg
  setup.py
Labels: enhancement, bot:chronographer:provided

#553 Ensure support for Python 3.12 and PyPy 3.8-3.10
  .github/workflows/ci-cd.yml
  CHANGES/553.packaging.rst
  setup.cfg
  tox.ini
Labels: bot:chronographer:provided

#561 🧪 Collect Cython coverage in CI
  .codecov.yml
  .coveragerc
  .github/workflows/ci-cd.yml
  CHANGES/560.contrib.rst
  CHANGES/561.contrib.rst
  MANIFEST.in
  codecov.yml
  docs/spelling_wordlist.txt
Labels: bot:chronographer:provided

#564 📝 Add change note guidelines to docs
  CHANGES/564.contrib.rst
  CHANGES/README.rst
  docs/contributing/guidelines.rst
  docs/index.rst
  docs/spelling_wordlist.txt
Labels: documentation, bot:chronographer:provided

#563 📝 Publish a release guide
  CHANGES/563.contrib.rst
  docs/contributing/release_guide.rst
  docs/index.rst
  docs/spelling_wordlist.txt
Labels: documentation, bot:chronographer:provided

#571 🐛 Fix `__class_getitem__` signature in classes
  .codecov.yml
  CHANGES/567.bugfix.rst
  CHANGES/571.bugfix.rst
  frozenlist/__init__.py
  frozenlist/_frozenlist.pyx
  tests/test_frozenlist.py
Labels: bug, bot:chronographer:provided

#572 🧪 Split typing-stubs & packaging coverage targets
  .codecov.yml
Labels: bot:chronographer:skip
